add_TGBot_project_start
PavelBoPavel/registration-TGBot pull request #3
Opened 2021-08-06 07:21 UTC by PavelBoPavel

реализовано:
 - прохождение по кнопкам месяца, дней, часов, описание, контакты

2021-08-06 07:30 UTC, Puzzletania approved these changes

2021-08-06 14:25 UTC, VasiliZas approved these changes

2021-08-07 18:18 UTC, trump-ny approved these changes

2021-08-08 19:10 UTC, Puzzletania approved these changes

2021-08-09 09:10 UTC, KaydunovDenis requested changes
Good gob!
This is hard for me. If you can, create a smaller pull request next time.
30 files  takes a lot of time.
I neen more time for good review.
See my comment. I did several remark.

2021-08-09 09:10 UTC, KaydunovDenis commented on src/test/java/com/github/pavelbo/registrationbot/FitbotApplicationTests.java
> +	}
I guess is don't must by empty.

2021-08-09 09:10 UTC, KaydunovDenis commented on src/test/java/com/github/pavelbo/registrationbot/service/TelegramBotTest.java
> +//    @Test
Почему закоментированно?

2021-08-09 09:10 UTC, KaydunovDenis commented on src/main/java/com/github/pavelbo/registrationbot/util/UpdateTypeUtil.java
> +        }
I think it need separete or rewrite on swith.

2021-08-09 09:10 UTC, KaydunovDenis commented on src/main/java/com/github/pavelbo/registrationbot/keyboard/ReplayKeyboardService.java
> +        KeyboardRow row2 = new KeyboardRow();
I think we can use "var" here

2021-08-09 09:10 UTC, KaydunovDenis commented on src/main/java/com/github/pavelbo/registrationbot/keyboard/ReplayKeyboardService.java
> +        keyBoardMarkup.setResizeKeyboard(true);
This code duplicate part code from the methode above.
I think can extract method here.

2021-08-09 09:10 UTC, KaydunovDenis commented on src/main/java/com/github/pavelbo/registrationbot/keyboard/ReplayKeyboardService.java
> +        return keyBoardMarkup;
This code duplicate part code from the methode above.
I think can extract method here

2021-08-09 09:10 UTC, KaydunovDenis commented on src/main/java/com/github/pavelbo/registrationbot/service/CallbackAnotherProcessor.java
> +                messageService.sendMessage(getChatId(update), "Contact!", inlineKeyboardSource.getKeyboardMain());
Best practic create String constant for it.

2021-08-09 09:10 UTC, KaydunovDenis commented on src/main/java/com/github/pavelbo/registrationbot/service/CallbackAnotherProcessor.java
> +                messageService.sendMessage(getChatId(update), "Do no!", inlineKeyboardSource.getKeyboardMain(), replayKeyboardService.getReplayKeyboardMain());
Best practic create String constant for it.

2021-08-09 09:10 UTC, KaydunovDenis commented on src/main/java/com/github/pavelbo/registrationbot/service/CallbackHourProcessor.java
> +                //saveFile(update);
You can to write
//TODO come doing, realise new function here.... etc

2021-08-09 09:10 UTC, KaydunovDenis commented on src/main/java/com/github/pavelbo/registrationbot/service/ContactProcessor.java
> +        messageService.sendMessage(getChatId(update),"Авторизация прошла успешно!", replayKeyboardService.getReplayKeyboardMain());
Best practic create String constant for it.

2021-08-09 09:10 UTC, KaydunovDenis commented on src/main/java/com/github/pavelbo/registrationbot/service/DefaultProcessor.java
> +        messageService.sendMessage(getChatId(update),"Неизвестная для бота команда!", replayKeyboardService.getReplayKeyboardMain());
Best practic create String constant for it.

2021-08-09 09:10 UTC, KaydunovDenis commented on src/main/java/com/github/pavelbo/registrationbot/util/ChatIdExtractor.java
> +        return null;
The null can throw NullPointException.
It is not good practic.
I think we need to throw the error or handle it elsewhere.

2021-08-09 10:03 UTC, KaydunovDenis approved these changes

2021-08-15 14:27 UTC, KaydunovDenis commented
Мы с этим что-то будем делать? может как то смержим? А потом уже будем его чинить?

2021-09-25 22:50 UTC, closed without merging